instruments:
  d1:
    adapter: psu.toml
    resource: USB0::1::INSTR
pipeline:
  record: all
tasks:
  - steps:
      - call: set_voltage
        instrument: d1
        args:
          voltage: 5
          channels:
            - 1
            - 2
